### ISSUE TITLE
Polywrap Repo QA Checklist

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/react#1]
Starting to think more about having a "QA Checklist" for repos we spin up. Here's a shot at creating one for this repo. Feel free to make these into individual issues.

- [ ] Branching
  - [ ] release branch(es)
    - [ ] no direct push access
    - [ ] PRs require 1 or more maintainer sign-offs
    - [ ] require CI to pass
- [ ] Continuous Integration
  - [ ] run on all PRs
- [ ] Continuous Deployment
  - [ ] defined process for bumping version
  - [ ] defined process for maintaining a CHANGELOG
  - [ ] published to github repo's release section
  - [ ] branch tag per release
  - [ ] published to package-specific repository (npm, crates.io, pip, wrappers.io, etc)
- [ ] README
  - [ ] Name of package
  - [ ] Description of purpose
  - [ ] Links to package URIs (source code, published artifacts, etc)
  - [ ] Versions of underlying technological standards
    - [ ] examples: "WRAP 0.1", "Polywrap JS Client 0.5-0.9"
  - [ ] Usage examples (code snippets)
    - [ ] Snippets are verifiably accurate, as they're built & run within the CI process.
    - [ ] Snippets are automatically injected into the README (see `doc-snippets` tool).
